common: &common
  adapter: postgresql
  username: postgres
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] || 'localhost' %>
  port: <%= ENV['DB_PORT_5432_TCP_PORT'] || '5432' %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  encoding: UTF8

development:
  <<: *common
  database: osp_development

test: &test
  <<: *common
  database: osp_test

production:
  <<: *common
  database: osp_production
